### ISSUE TITLE
Add macOS Support

### ISSUE THREAD

**Issue by Sherlouk** [alexey1312/SnapshotTestingHEIC#1]
Would you ever consider adding macOS support? Would be good to reuse as much of the logic as possible as there are a bunch of similarities between the NSImage and UIImage interfaces used for this extension.

**Comment by alexey1312** [comment]
Hmm, good idea! I can try to add this functionality a bit later.

**Comment by Sherlouk** [comment]
The reason being is that I use SnapshotTesting with Vapor to take screenshots of my webpages 😄  Would be great to have the space saving of HEIC too.

**Comment by alexey1312** [comment]
#2 seems ready
