### ISSUE TITLE
Snapshots crash on simulator 17.5

### ISSUE THREAD

**Issue by notapplicableio** [alexey1312/SnapshotTestingHEIC#10]
In the `heicData(compressionQuality: CompressionQuality = .lossless) -> Data?`, `CGImageDestinationFinalize(imageDestination)` has a h1v1 codec issue. This is fine in the previous simulator.

**Comment by notapplicableio** [comment]
Is anyone else seeing this? Or just me? @alexey1312

**Comment by terminox** [comment]
I'm facing the same issue ✋

**Comment by fruitcoder** [comment]
Is this still an issue on the current Xcode 16 Betas? Maybe we could make the `compressionQuality` optional so the `options` are empty. This could be a temporary fix https://forums.developer.apple.com/forums/thread/755470

**Comment by alexey1312** [comment]
Hello. Please check the latest version - 1.5.0
