### ISSUE TITLE
Support for perceptualPrecision parameter

### ISSUE THREAD

**Issue by sschizas** [alexey1312/SnapshotTestingHEIC#5]
In the latest version (1.10.0) of snapshot testing framework a new parameter has been introduced: `perceptualPrecision`. Are there any plans to support it?

**Comment by alexey1312** [comment]
Уes, there are plans

**Comment by iwb-omar-belhaouss** [comment]
@alexey1312 Any update about that please?

**Comment by alexey1312** [comment]
@iwb-omar-belhaouss Hey, I added this parameter [here](https://github.com/alexey1312/snapshottestingheic/releases/tag/1.3.0).
it took so long 😬
Can I close the issue?)

**Comment by tfe** [comment]
Thanks for adding this @alexey1312! I appreciate your work on this. Would it make sense to add the parameter to the Snapshotting extension for UIViewController also? That's where I need it in my project.

**Comment by tfe** [comment]
I went ahead and took a shot at it here: https://github.com/alexey1312/SnapshotTestingHEIC/pull/8.

**Comment by alexey1312** [comment]
@tfe , thank you for your contribution, I have already [published](https://github.com/alexey1312/SnapshotTestingHEIC/releases/tag/1.3.2) it!

**Comment by iwb-omar-belhaouss** [comment]
@alexey1312 thank you for adding this! You can close the issue 🎉
